# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/kglobalaccel': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'plasma/plasma-activities': '@latest-kf6'
    'graphics/libkdcraw': '@same'
    'libraries/phonon': '@latest-kf6'
    'third-party/wayland': '@latest'
    'third-party/wayland-protocols': '@latest'
