#cmakedefine GWENVIEW_SEMANTICINFO_BACKEND_NONE 1
#cmakedefine GWENVIEW_SEMANTICINFO_BACKEND_FAKE 1
#cmakedefine GWENVIEW_SEMANTICINFO_BACKEND_BALOO 1
#cmakedefine KIPI_FOUND 1
#define GV_TEST_DATA_DIR "@CMAKE_CURRENT_SOURCE_DIR@/tests/data"
#cmakedefine HAVE_X11 ${HAVE_X11}
#cmakedefine HAVE_FITS ${HAVE_FITS}
