#cmakedefine GWENVIEW_SEMANTICINFO_BACKEND_NONE 1
#cmakedefine GWENVIEW_SEMANTICINFO_BACKEND_FAKE 1
#cmakedefine GWENVIEW_SEMANTICINFO_BACKEND_BALOO 1
#define GV_TEST_DATA_DIR "@CMAKE_CURRENT_SOURCE_DIR@/tests/data"
#cmakedefine HAVE_X11 ${HAVE_X11}
#cmakedefine HAVE_FITS ${HAVE_FITS}
#cmakedefine HAVE_QTDBUS ${HAVE_QTDBUS}
#cmakedefine01 HAVE_KACTIVITIES
#cmakedefine01 HAVE_PURPOSE
#cmakedefine HAVE_TIFF 1
#cmakedefine KIMAGEANNOTATOR_FOUND ${KIMAGEANNOTATOR-Qt6_FOUND}
#cmakedefine GWENVIEW_NO_WAYLAND_GESTURES 1
