[Desktop Entry]
Name=Gwenview
Name[ar]=جوِينفيو
Name[ast]=Gwenview
Name[az]=Gwenview
Name[be]=Gwenview
Name[bg]=Gwenview
Name[bs]=Gwenview
Name[ca]=Gwenview
Name[ca@valencia]=Gwenview
Name[cs]=Gwenview
Name[da]=Gwenview
Name[de]=Gwenview
Name[el]=Gwenview
Name[en_GB]=Gwenview
Name[eo]=Gwenview
Name[es]=Gwenview
Name[et]=Gwenview
Name[eu]=Gwenview
Name[fa]=Gwenview
Name[fi]=Gwenview
Name[fr]=Gwenview
Name[ga]=Gwenview
Name[gl]=Gwenview
Name[he]=Gwenview
Name[hi]=ग्वेन-व्यू
Name[hne]=ग्वेन-व्यू
Name[hr]=Gwenview
Name[hsb]=Gwenview
Name[hu]=Gwenview
Name[ia]=Gwenview
Name[id]=Gwenview
Name[ie]=Gwenview
Name[is]=Gwenview
Name[it]=Gwenview
Name[ja]=Gwenview
Name[ka]=Gwenview
Name[kk]=Gwenview
Name[km]=Gwenview
Name[ko]=Gwenview
Name[ku]=Gwenview
Name[lt]=Gwenview
Name[lv]=Gwenview
Name[ml]=ഗ്വെൻവ്യൂ
Name[mr]=ग्वेनव्यु
Name[nb]=Gwenview
Name[nds]=Gwenview
Name[ne]=जीवेनभ्यू
Name[nl]=Gwenview
Name[nn]=Gwenview
Name[oc]=Gwenview
Name[pa]=ਗਵਿਨ-ਵਿਊ
Name[pl]=Gwenview
Name[pt]=Gwenview
Name[pt_BR]=Gwenview
Name[ro]=Gwenview
Name[ru]=Gwenview
Name[si]=Gwenview
Name[sk]=Gwenview
Name[sl]=Gwenview
Name[sr]=Гвенвју
Name[sr@ijekavian]=Гвенвју
Name[sr@ijekavianlatin]=GwenView
Name[sr@latin]=GwenView
Name[sv]=Gwenview
Name[ta]=குவென்வியூ
Name[th]=เกวนวิว
Name[tr]=Gwenview
Name[ug]=Gwenview
Name[uk]=Gwenview
Name[vi]=Gwenview
Name[x-test]=xxGwenviewxx
Name[zh_CN]=Gwenview 图像查看器
Name[zh_TW]=Gwenview
GenericName=Image Viewer
GenericName[ar]=عارض صور
GenericName[ast]=Visor de semeyes
GenericName[be]=Сродак для прагляду выяў
GenericName[bg]=Преглед на изображения
GenericName[ca]=Visualitzador d'imatges
GenericName[ca@valencia]=Visor d'imatges
GenericName[cs]=Prohlížeč obrázků
GenericName[en_GB]=Image Viewer
GenericName[eo]=Bildrigardilo
GenericName[es]=Visor de imágenes
GenericName[eu]=Irudi erakuslea
GenericName[fi]=Kuvakatselin
GenericName[fr]=Visionneuse d'images
GenericName[he]=מציג תמונות
GenericName[hu]=Képmegjelenítő
GenericName[ia]=Visor de Image
GenericName[is]=Myndskoðari
GenericName[it]=Visore di immagini
GenericName[ja]=画像ビューア
GenericName[ka]=სურათების გალერეა
GenericName[ko]=그림 뷰어
GenericName[lt]=Paveikslų žiūryklė
GenericName[lv]=Attēlu skatītājs
GenericName[nl]=Afbeeldingsviewer
GenericName[pa]=ਚਿੱਤਰ ਦਰਸ਼ਕ
GenericName[pl]=Przeglądarka obrazów
GenericName[pt_BR]=Visualizador de imagens
GenericName[ro]=Vizualizator de imagini
GenericName[ru]=Приложение для просмотра изображений
GenericName[sk]=Prezerač obrázkov
GenericName[sl]=Pregledovalnik slik
GenericName[sv]=Bildvisare
GenericName[ta]=படக் காட்டி
GenericName[tr]=Görsel Görüntüleyicisi
GenericName[uk]=Переглядач зображень
GenericName[x-test]=xxImage Viewerxx
GenericName[zh_CN]=图像查看器
GenericName[zh_TW]=影像檢視器
Comment=A simple image viewer
Comment[ar]=عارض صور بسيط
Comment[az]=Sadə şəkilə baxış vasitəsi
Comment[be]=Просты рухавік для прагляду выяў
Comment[bg]=Програма за преглед на изображения
Comment[bs]=Jednostavan prikazivač slika
Comment[ca]=Un visualitzador d'imatges senzill
Comment[ca@valencia]=Un visor d'imatges senzill
Comment[cs]=Jednoduchý prohlížeč obrázků
Comment[da]=Simpel billedfremviser
Comment[de]=Ein einfacher Bildbetrachter
Comment[el]=Ένας απλός προβολέας εικόνων
Comment[en_GB]=A simple image viewer
Comment[eo]=Simpla bildorigardilo
Comment[es]=Un visor de imágenes sencillo
Comment[et]=Lihtne pildinäitaja
Comment[eu]=Irudi erakusle erraz bat
Comment[fa]=مشاهده‌گر تصویر  ساده
Comment[fi]=Yksinkertainen kuvankatselin
Comment[fr]=Un afficheur simple d'images
Comment[ga]=Amharcán simplí íomhánna
Comment[gl]=Un visor de imaxes sinxelo.
Comment[he]=מציג תמונות פשוט
Comment[hi]=एक सरल चित्र प्रदर्शक
Comment[hne]=एक सरल फोटू प्रदर्सक
Comment[hr]=Jednostavni preglednik slika
Comment[hsb]=Jednory wobhladowar za wobrazy
Comment[hu]=Egyszerű képnézegető
Comment[ia]=Un simplice visor de imagine
Comment[id]=Sebuah penampil citra sederhana
Comment[ie]=Un simplic visor de images
Comment[is]=Einfaldur myndskoðari
Comment[it]=Un semplice visore di immagini
Comment[ja]=シンプルな画像ビューア
Comment[ka]=მარტივი სურათების გალერეა
Comment[kk]=Қарапайым кескінді қарау құралы
Comment[km]=កម្មវិធី​មើល​រូបភាព​ធម្មតា
Comment[ko]=간단한 그림 뷰어
Comment[ku]=Nîşanderê wêneyan yê hêsanî
Comment[lt]=Paprasta paveikslų žiūryklė
Comment[lv]=Vienkāršs attēlu skatītājs
Comment[ml]=ഒരു ലളിതമായ ചിത്രദര്‍ശിനി
Comment[mr]=एक सोपा प्रतिमा प्रदर्शक
Comment[nb]=En enkel bildeviser
Comment[nds]=En eenfach Bildkieker
Comment[nl]=Een eenvoudige afbeeldingsviewer
Comment[nn]=Ein enkel biletvisar
Comment[pa]=ਇੱਕ ਸਰਲ ਚਿੱਤਰ ਦਰਸ਼ਕ
Comment[pl]=Prosta przeglądarka obrazów
Comment[pt]=Um visualizador de imagens simples
Comment[pt_BR]=Um visualizador simples de imagens
Comment[ro]=Un vizualizator de imagini simplu
Comment[ru]=Просмотр изображений
Comment[si]=සරල පිංතූර දසුන
Comment[sk]=Jednoduchý prehliadač obrázkov
Comment[sl]=Preprost pregledovalnik slik
Comment[sr]=Једноставан приказивач слика
Comment[sr@ijekavian]=Једноставан приказивач слика
Comment[sr@ijekavianlatin]=Jednostavan prikazivač slika
Comment[sr@latin]=Jednostavan prikazivač slika
Comment[sv]=En enkel bildvisare
Comment[ta]=ஓர் எளிய படக் காட்டி
Comment[th]=เครื่องมือแสดงภาพแบบพื้นฐาน
Comment[tr]=Yalın bir görsel görüntüleyicisi
Comment[ug]=ئاددىي سۈرەت كۆرگۈ
Comment[uk]=Простий переглядач зображень
Comment[vi]=Bộ xem ảnh đơn giản
Comment[x-test]=xxA simple image viewerxx
Comment[zh_CN]=简易图像查看器
Comment[zh_TW]=一個簡單的影像檢視程式
Exec=gwenview %U
Icon=gwenview
Type=Application
Categories=Qt;KDE;Graphics;Viewer;Photography;
MimeType=inode/directory;${IMAGE_MIME_TYPES};
X-DocPath=gwenview/index.html
# InitialPreference should be greater than Okular so that Gwenview is the
# primary application associated with images, but less than Konqueror or Dolphin
# so that Gwenview is not the primary applications for folders.
InitialPreference=8
X-DBUS-ServiceName=org.kde.gwenview
