.TH "gwenview" "1" "0.11.0" "Michael Spanier" "An Image Viewer for KDE"
.SH "NAME"
.LP 
gwenview \- an imageviewer for KDE 
.SH "SYNTAX"
.LP 
gwenview 
.br 
.SH "DESCRIPTION"
.LP 
gwenview is an imageviewer for KDE.
It features a folder tree window and a file list window to provide easy navigation in your file hierarchy.
.
Image loading is done by the Qt library, so it supports all image formats your Qt installation supports. Gwenview correctly displays images with alpha channels. 

It uses docked windows, so you can alter the layout in any way you want. You can also browse your images in full screen. 
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.SH "AUTHORS"
.LP 

Aurelien Gateau <aurelien.gateau@mail.dotcom.fr>

This manual page was written by Michael Spanier <mail@michael\-spanier.de> for the Debian GNU/Linux system (but may be used by others).
