.TH "gwenview" "1" "0.15.0" "Michael Spanier" "An Image Viewer for KDE"
.SH "NAME"
.LP 
gwenview \- an imageviewer for KDE 
.SH "SYNTAX"
.LP 
gwenview [file or folder]
.br 
.SH "DESCRIPTION"
.LP 
gwenview is an image viewer for KDE.
It features a folder tree window and a file list window to provide easy navigation in your file hierarchy.
.
Image loading is done by the Qt library, so it supports all image formats your Qt installation supports. Also support for the XCF file format has been added. Gwenview correctly displays images with alpha channels. 

It uses docked windows, so you can alter the layout in any way you want. You can also browse your images in full screen. 

Gwenview can be start with a file or a folder as a optionally argument. If a file is given gwenview will show this file, if a folder is given gwenview will show the content of the folder as perview.
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.SH "AUTHORS"
.LP 

Aurelien Gateau <aurelien.gateau@free.fr>

This manual page was written by Michael Spanier <mail@michael\-spanier.de> for the Debian GNU/Linux system (but may be used by others).
